In [41]:
data = {
    "Brand": ["Maruti", "Hyundai", "Maruti", "Honda", "Toyota", "Honda"],
    "Year": [2018, 2017, 2018, 2016, 2019, 2015],
    "Fuel": ["Petrol", "Diesel", "Petrol", "Petrol", "Diesel", "Petrol"],
    "KMs_Driven": [30000, 40000, 30000, None, 20000, 70000],
    "Price": [400000, 500000, 400000, 450000, 800000, -200000],
}

TASK-1

In [42]:
import numpy as np
import pandas as pd

In [43]:
df= pd.DataFrame(data)

In [44]:
df.head()

     Brand  Year    Fuel  KMs_Driven   Price
0   Maruti  2018  Petrol     30000.0  400000
1  Hyundai  2017  Diesel     40000.0  500000
2   Maruti  2018  Petrol     30000.0  400000
3    Honda  2016  Petrol         NaN  450000
4   Toyota  2019  Diesel     20000.0  800000

In [45]:
df.isnull().sum()

Brand         0
Year          0
Fuel          0
KMs_Driven    1
Price         0
dtype: int64

TASK-2

Filling missing values

In [46]:
df['KMs_Driven']= df['KMs_Driven'].fillna(df['KMs_Driven'].median())

In [47]:
df= df[df['Price']>0]

In [48]:
df= df.drop_duplicates()

In [49]:
df

     Brand  Year    Fuel  KMs_Driven   Price
0   Maruti  2018  Petrol     30000.0  400000
1  Hyundai  2017  Diesel     40000.0  500000
3    Honda  2016  Petrol     30000.0  450000
4   Toyota  2019  Diesel     20000.0  800000

TASK-3

In [50]:
mapping= {'Petrol':1,'Diesel':2}
df['Fuel']= df['Fuel'].map(mapping)

In [51]:
df= pd.get_dummies(df, columns=['Brand']).astype(int)

In [52]:
x= df.drop(columns=['Price'])
y= df['Price']

In [53]:
print(x)
print(y)

   Year  Fuel  KMs_Driven  Brand_Honda  Brand_Hyundai  Brand_Maruti  \
0  2018     1       30000            0              0             1
1  2017     2       40000            0              1             0
3  2016     1       30000            1              0             0
4  2019     2       20000            0              0             0

   Brand_Toyota
0             0
1             0
3             0
4             1
0    400000
1    500000
3    450000
4    800000
Name: Price, dtype: int64

In [54]:
df

,Year,Fuel,KMs_Driven,Price,Brand_Honda,Brand_Hyundai,Brand_Maruti,Brand_Toyota
0,2018,1,30000,400000,0,0,1,0
1,2017,2,40000,500000,0,1,0,0
3,2016,1,30000,450000,1,0,0,0
4,2019,2,20000,800000,0,0,0,1